function [x_nn, c] = model_loose_1d(x_n, u_n, t, inp)
%[x_nn, c] = MODEL_LOOSE_1D(x_n, u_n, t, inp)
%	Returns the next state x_nn and cost c when applying the control u to
%	the system state x_n at time t and with general inputs inp for the
%	one-dimensional approximation of the loosely coupled two-dimensional
%	problem.
% The one-dimensional approximation is generated by neglecting the dynamics
% of the 'fast' state variable and assuming the 'fast' state variable can
% be set to an arbitrary value at any given time.
%
% In this case, this results in the one-dimensional system
%
%	y[k+1] = y[k] + u[k] * delta_t
%	
%	where we want to solve u for
%
%	min(sum((|y| + |u/10|) * delta_t, k = 0, k = N))
%
%	where delta_t is the sampling period and subject to
%
%	y(0) = y0
%	y(N) = y_T
%	u_min <= u <= u_max
%
%	The use of the 1-norm in the cost function ensures that the optimal
%	solution results in bang-bang control of u.
%


x_nn = x_n + u_n * inp.T_s;

c = sum((abs(x_n) + 1/10 * abs(u_n)) * inp.T_s, 2);

end

