function bsfc = calc_bsfc(w, tau)
%CALC_BSFC Calculates the instantaneous brake-specific-fuel-consumption for
%a given engine.
%
%Function generated by gen_bsfc_funs.m
%DO NOT MODIFY THIS FUNCTION! Create function using gen_bsfc_funs.m!
%
%#!KEYSTR_BSFC_94ed5811c494d0e7186a6d05ab5e584e
bsfc_f = @(tau,w)sqrt(abs(tau-5.0e1).^2.*2.5e-19+abs(w-1.2e2).^2.*4.0e-20)+5.555555555555555e-8;

bsfc = bsfc_f(tau, w);
